#!/bin/bash

SOLC=`which solc`
FLAGS=" --rpc --rpcapi web3,eth,miner --solc $SOLC --mine --etherbase 0 --networkid 54321 --nodiscover"
N=5	# default setting for initial accounts. should fix flag to support this

if [ -d 'geth'  ]; then
	PREFIX='./geth'
else
	PREFIX='.'
fi

if [ ! -d "$HOME/.ethereum" ]; then
	rm "$PREFIX/pass" &> /dev/null
	echo "Initializing genesis block..."
	geth init ""$PREFIX"/genesis.json"

	if [ $# != 0 ]; then
		N="$1"
	fi
	echo
	if [ "$N" = 1 ]; then
		echo "Creating 1 account"
	else 
		echo "Creating $N accounts..."
	fi
	n=`expr "$N" - 1`
	for i in `seq 0 $n`
	do
		echo 'lol' >> "$PREFIX/pass"
		geth --password "$PREFIX/pass" account new
	done
fi


FLAGS=$FLAGS" --unlock 0,1,2,3,4 --password $PREFIX/pass"
echo
echo "Starting geth node (see geth.log for detail)"
nohup geth $FLAGS > "$PREFIX/geth.log" 2>&1 &
echo "To connect, run 'node console'"
